import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <h1> Hola mundo</h1>
      </main>

    
    </Layout>
  )
}
